# Job growth

```{r}
library(lehdr)
library(sf)
dane_county <- tigris::block_groups(55, 25, cb = T)
jobs_2019 <- grab_lodes(state = "WI", 
                   year = 2019, 
                   lodes_type = "wac", 
                   agg_geo = "bg",
                   use_cache = TRUE)

jobs_2015 <- grab_lodes(state = "WI", 
                   year = 2015, 
                   lodes_type = "wac", 
                   agg_geo = "bg",
                   use_cache = TRUE)

jobs_change <- rbind(jobs_2015, jobs_2019) |> 
  select(year, C000, w_bg) |> 
  pivot_wider(names_from = year, 
              values_from = C000,
              names_prefix = "jobs_") |> 
  mutate(job_growth = jobs_2019 - jobs_2015) 

jobs_change <- dane_county |> 
  left_join(jobs_change, by = join_by(GEOID == w_bg)) |> 
  filter(ALAND != 0) 

tm_shape(jobs_change) +
  tm_polygons("job_growth", style = "jenks",
              alpha = .7)


jobs_dane <- dane_county |> 
  left_join(jobs, by = join_by(GEOID == w_bg)) |> 
  filter(ALAND != 0) |> 
  mutate(jobs_per_acre = C000/(ALAND*0.0002471054))

library(tmap)
tmap_mode("view")
tm_shape(jobs_dane) +
  tm_polygons(col = "jobs_per_acre", style = "jenks",
              alpha = .7)

```

Could try comparing job growth with BNA score
 - maybe not available at BG level? Maybe not available beyond city limits?
 
could also run analysis with distance from capitol (43.074722, -89.384167) -- that'd be fun

# BNA
```{r}
bna_blocks <- st_read("data/neighborhood_census_blocks/neighborhood_census_blocks.shp")


bna_blocks_geoid <- bna_blocks |> 
  mutate(block_group_geoid = str_trunc(BLOCKID10, 
                                       width = 12, 
                                       side = "right",
                                       ellipsis = ""
                                      )) |> 
  summarize(bna_score_bg = mean(OVERALL_SC, na.rm = T), .by = block_group_geoid)
jobs_change |> 
  left_j
  
bna_blocks_geoid |> st_drop_geometry() |> 
  left_join(dane_county, by = join_by(block_group_geoid == GEOID)) |> class()
  tm_shape() +
  tm_polygons("bna_score_bg")
bna_ways <- st_read("data/neighborhood_ways/neighborhood_ways.shp")
tmap_mode("view")
bna_blocks |> 
  tm_shape() +
  tm_polygons("OVERALL_SC")
```




